<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>AlumniCRM - Dashboard</title>

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

	<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />

	<link href="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.4.0/min/dropzone.min.css" rel="stylesheet" />
	<script src="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.4.0/min/dropzone.min.js"></script>

    <link href="<?=Helper::url('/media/css/dashboard.css')?>" rel="stylesheet" />
    
    <script src="<?=Helper::url('/media/js/import.js')?>" rel="stylesheet"></script>

	<script src="<?=Helper::url('/media/js/global.js')?>"></script>

	<style>
		#cover {
			background: url("<?=Helper::url('/media/spinner.gif')?>") no-repeat scroll center center #FFF;
			position: absolute;
			height: 100%;
			width: 100%;
		}

		.dropzone {
		  border: 2px dashed #0087F7;
		  border-radius: 5px;
		  background: white;}
		  .dropzone .dz-message {
			font-weight: 400; }
			.dropzone .dz-message .note {
			  font-size: 0.8em;
			  font-weight: 200;
			  display: block;
			  margin-top: 1.4rem;
		}
	</style>

    <script>
		
		$(document).ready(function () {
			$('#cover').fadeOut(1000);

			Dropzone.options.dzone = {
				init: function () {
					this.on("addedfile", function (file) {
						$('#cover').fadeIn(10);
					});

					this.on("complete", function () {
						$('#cover').fadeOut(1000);
					});

					this.on("success", function (val) {
						console.log(val);
					});

					this.on("error", function (val, error) {
						alert(error);
					});
				},
				acceptedFiles: ".csv"
			};
		});

		
		
    </script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

	<div id="cover"></div>

    <!-- Top menu -->
    <?php include "components/top-menu.php"; ?>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
			<!-- LHS Menu -->
			<?php include "components/lhs-menu.php"; ?>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
			<h1 class="page-header">Import</h1>
			<div class="row">
				<div class="col-lg-12">				
					<i class="fa fa-spinner" id="spinner" aria-hidden="true"></i>

					<form action="<?=Helper::url('/api/v1/customer/import')?>" method="POST" class="dropzone" id="dzone">
						<div class="fallback">
							<input name="file" type="file" multiple />
						</div>
						<div class="dz-message">Drop files here or click to upload.</div>
					</form>
				</div>
			</div>
          
			<h1 class="page-header" style="margin-top:3%;">Export</h1>
			<div class="row" style="margin-top:2%;">
				<div class="col-lg-12">
					<a class="btn btn-success" href="<?=Helper::url('/api/v1/customer/export')?>">Export data <i class="fa fa-file"></i></a>
				</div>
			</div>
          
        </div>
      </div>
    </div>
    
  </body>
</html>
