<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>AlumniCRM - Dashboard</title>

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

	<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />

	<link href="https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap.min.css" rel="stylesheet" />
	
	<script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
	
	<script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap.min.js"></script>

    <link href="<?=Helper::url('/media/css/dashboard.css')?>" rel="stylesheet" />

	<script src="<?=Helper::url('/media/js/global.js')?>"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    
    <script>
		$(document).ready(function() {
			$('#data_table').DataTable({
				"order": [1, 'desc'],
				"initComplete": function (settings, json) {
					$('#cover').fadeOut(1000);
				}
			});
			
			$(".email").click(function () {
				var href = $(this).attr('href');
			
				var emails = [];
				$('input[name=emails]:checked').each(function() {
					emails.push($(this).val());
				});
			
				window.location.href = (href + "?to=" + emails.join(','));
				
				return false;
			});
		} );
    </script>
    
  </head>

  <body>

	<!-- Page load spinner -->
    <?php include "components/spinner.php"; ?>

    <!-- Top menu -->
    <?php include "components/top-menu.php"; ?>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
			<!-- LHS Menu -->
			<ul class="nav nav-sidebar">
				<li class="active"><a href="<?=Helper::url('/alumni')?>">Alumni</a></li>
				<li><a href="<?=Helper::url('/alumni/import')?>">Import / Export</a></li>
				<li><a href="<?=Helper::url('/email')?>">Email</a></li>
			</ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          <h1 class="page-header">Alumni Section</h1>
          
          <div class="row" style="margin-bottom:2%;">
			<div class="col-lg-12">				
				<a class="btn btn-default btn-lg pull-right" href="<?=Helper::url('/alumni/create')?>">Create <i class="fa fa-plus"></i></a>
				<a class="btn btn-default btn-lg pull-right email" style="margin-right:1%;" href="<?=Helper::url('/email/compose')?>">Email <i class="fa fa-envelope"></i></a>
			</div>
          </div>
          
          <!-- Content goes here -->
          <div class="row">
			<div class="col-lg-12 table-responsive">
				<table class="table table-striped" id="data_table">
				  <thead>
					<tr>
						<th>  </th>
						<th>ID</th>
						<th>Name</th>
						<th>Email</th>
						<th>School</th>
						<th>Degree</th>
						<th>Major</th>
						<th>Can Contact</th>
						<th>Actions</th>
					</tr>
				  </thead>
				  <tbody>
				  <?php if ($customers->num_rows > 0): ?>
				  <?php while ($customer = $customers->fetch_assoc()): ?>
					<tr
					<?php if (! empty($customer['blocked_by'])): ?>
						class="danger"
					<?php endif; ?>
					>
						<td><input type="checkbox" name="emails" value="<?=$customer['email']?>"></td>
						<td><?=$customer['id_customer']?></td>
						<td><?=($customer['first_name']." ".$customer['last_name'])?></td>
						<td><?=$customer['email']?></td>
						<td><?=$customer['school']?></td>
						<td><?=$customer['degree']?></td>
						<td><?=$customer['major']?></td>

						<?php if (! empty($customer['blocked_by'])): ?>
						<td>No</td>
						<?php else: ?>
						<td>Yes</td>
						<?php endif; ?>
						
						<td>
							<a class="btn btn-primary" href="<?=Helper::url('/alumni/'.$customer['id_customer'])?>">View</a>
						</td>
					</tr>
					<?php endwhile; ?>
					<?php endif; ?>
				  </tbody>
				</table>
			</div>
          </div>
          
        </div>
      </div>
    </div>

  </body>
</html>
