<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>AlumniCRM - Dashboard</title>

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <link href="<?=Helper::url('/media/css/dashboard.css')?>" rel="stylesheet" />

	<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/dashboard">Alumni CRM</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="<?=Helper::url('/dashboard')?>">Dashboard</a></li>
            <li><a href="<?=Helper::url('/auth/register')?>">Create Admin</a></li>
            <li><a href="<?=Helper::url('/auth/login')?>">Login</a></li>
            <li><a href="<?=Helper::url('/api/v1/logout')?>">Logout</a></li>
          </ul>
          
        </div>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li><a href="<?=Helper::url('/dashboard')?>">Overview</a></li>
            <li class="active"><a href="<?=Helper::url('/alumni')?>">Alumni <span class="sr-only">(current)</span></a></li>
            <li><a href="#">Email</a></li>
            <li><a href="#">Export / Import</a></li>
          </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          <h1 class="page-header">Alumni Section</h1>
          
          <!-- Content goes here -->
          <div class="row">
			<div class="col-lg-12">
				<div class="well">
					<div class="row">
						<div class="col-lg-8">
							<h2>Search</h2>
							
							<form class="form-inline">
							  <div class="form-group">
								<label for="exampleInputName2">Name</label>
								<input type="text" class="form-control" id="exampleInputName2" placeholder="Jane Doe">
							  </div>
							  <div class="form-group">
								<label for="exampleInputEmail2">Email</label>
								<input type="email" class="form-control" id="exampleInputEmail2" placeholder="jane.doe@example.com">
							  </div>
							  <button type="submit" class="btn btn-default">Send invitation</button>
							</form>
						</div>
						<div class="col-lg-4">
							<h2>Add new</h2>
							
							<a class="btn btn-primary" href="/alumni/create">Add <i class="fa fa-plus"></i></a>
						</div>
					</div>
					
				</div>
			</div>
          </div>
          
          <div class="row">
			<div class="col-lg-12">
				<table class="table table-striped">
				  <thead>
					<tr>
						<th>ID</th>
						<th>Name</th>
						<th>Email</th>
						<th>School</th>
						<th>Actions</th>
					</tr>
				  </thead>
				  <tbody>
					<tr>
						<td>1</td>
						<td>Ravi Malik</td>
						<td>ravimali@buffalo.edu</td>
						<td>UB</td>
						<td><a class="btn btn-primary" href="/alumni/1">View</a></td>
					</tr>
					<tr>
						<td>1</td>
						<td>Ravi Malik</td>
						<td>ravimali@buffalo.edu</td>
						<td>UB</td>
						<td><a class="btn btn-primary" href="/alumni/2">View</a></td>
					</tr>
				  </tbody>
				</table>
			</div>
          </div>
          
        </div>
      </div>
    </div>
    
  </body>
</html>
