<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>AlumniCRM - Dashboard</title>

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <link href="<?=Helper::url('/media/css/dashboard.css')?>" rel="stylesheet" />

	<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />

	<script src="<?=Helper::url('/media/js/alumni_create.js')?>"></script>

	<script src="<?=Helper::url('/media/js/global.js')?>"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <!-- Top menu -->
    <?php include "components/top-menu.php"; ?>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
			<!-- LHS Menu -->
			<ul class="nav nav-sidebar">
				<li class="active"><a href="<?=Helper::url('/alumni')?>">Alumni</a></li>
				<li><a href="<?=Helper::url('/alumni/import')?>">Import / Export</a></li>
				<li><a href="<?=Helper::url('/email')?>">Email</a></li>
			</ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          <h1 class="page-header">Add new alumni record</h1>
          
          <div class="row">
				<div class="col-lg-12">
					<form action="<?=Helper::url('/api/v1/customer')?>" method="POST">
						<div class="row">

							<div class="form-group col-lg-6">
								<label>First Name *</label>
								<input type="text" class="form-control" id="first_name" name="first_name"/>
							</div>
							<div class="form-group col-lg-6">
								<label>Last Name *</label>
								<input type="text" class="form-control" id="last_name" name="last_name"/>
							</div>
							<div class="form-group col-lg-6">
								<label>Email *</label>
								<input type="text" class="form-control" id="email" name="email"/>
							</div>
							<div class="form-group col-lg-6">
								<label>Degree *</label>
								<input type="text" class="form-control" id="degree" name="degree"/>
							</div>
							<div class="form-group col-lg-6">
								<label>Major *</label>
								<input type="text" class="form-control" id="major" name="major"/>
							</div>
							<div class="form-group col-lg-6">
								<label>School *</label>
								<input type="text" class="form-control" id="school" name="school"/>
							</div>
							<div class="form-group col-lg-6">
								<label>Type *</label>
								<select name="type" class="form-control" id="type">
									<option value="alumni">Alumni</option>
									<option value="current">Current</option>
								</select>
							</div>
							<div class="form-group col-lg-6">
								<label>Gender *</label>
								<select name="gender" class="form-control" id="gender">
									<option value="male">Male</option>
									<option value="female">Female</option>
								</select>
							</div>
							<div class="form-group col-lg-6">
								<label>Salutation *</label>
								<input type="text" class="form-control" id="salutation" name="salutation"/>
							</div>
							<div class="form-group col-lg-6">
								<label>Preferred Mail Name *</label>
								<input type="text" class="form-control" id="preferred_mail_name" name="preferred_mail_name"/>
							</div>
							<div class="form-group col-lg-6">
								<label>Birthday *</label>
								<input type="date" class="form-control" id="birthday" name="birthday"/>
							</div>
							<div class="form-group col-lg-6">
								<label>Active</label>
								<input type="checkbox" class="form-control" id="active" name="active" value="true"/>
							</div>
							<div class="form-group col-lg-6">
								<label>Home Street 1 *</label>
								<input type="text" class="form-control" id="home_street_1" name="home_street_1"/>
							</div>
							<div class="form-group col-lg-6">
								<label>Home Street 2</label>
								<input type="text" class="form-control" id="home_street_2" name="home_street_2"/>
							</div>
							<div class="form-group col-lg-6">
								<label>Country *</label>
								<input type="text" class="form-control" id="country" name="country"/>
							</div>
							<div class="form-group col-lg-6">
								<label>City *</label>
								<input type="text" class="form-control" id="city" name="city"/>
							</div>
							<div class="form-group col-lg-6">
								<label>State *</label>
								<input type="text" class="form-control" id="state" name="state"/>
							</div>
							<div class="form-group col-lg-6">
								<label>Zipcode *</label>
								<input type="text" class="form-control" id="zipcode" name="zipcode" pattern="[0-9]{5}" title="5 digit zipcode"/>
							</div>
							<div class="form-group col-lg-6">
								<label>Home Number</label>
								<input type="text" class="form-control" id="home_number" name="home_number"/>
							</div>
							<div class="form-group col-lg-6">
								<label>Phone Number *</label>
								<input type="text" class="form-control" id="phone_number" name="phone_number"/>
							</div>
							<div class="form-group col-lg-6">
								<label>Major year start *</label>
								<input type="date" class="form-control" id="major_year_start" name="major_year_start"/>
							</div>
							<div class="form-group col-lg-6">
								<label>Major year end *</label>
								<input type="date" class="form-control" id="major_year_end" name="major_year_end"/>
							</div>
							
							<div class="form-group col-lg-6">
								<button type="submit" class="btn btn-primary">Submit</button>
							</div>

						</div>
					</form>
				</div>
			</div>

        </div>
      </div>
    </div>

	<!-- Success Modal -->
	<?php include "components/success-modal.php"; ?>

	<!-- Error Modal -->
	<?php include "components/error-modal.php"; ?>

  </body>
</html>
