<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>AlumniCRM - Dashboard</title>

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

	<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />

	<link href="https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap.min.css" rel="stylesheet" />
	
	<script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
	
	<script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap.min.js"></script>

    <link href="<?=Helper::url('/media/css/dashboard.css')?>" rel="stylesheet" />

	<script src="<?=Helper::url('/media/js/alumni_single.js')?>"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <!-- Top menu -->
    <?php include "components/top-menu.php"; ?>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
			<!-- LHS Menu -->
			<?php include "components/lhs-menu.php"; ?>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
    
			<div class="row">
				<div class="col-lg-12">
					<form action="<?=Helper::url('/api/v1/customer/'.$customer['id_customer'])?>" method="POST">
						<fieldset>
							<legend>Base Info</legend>
							
							<div class="row">
								<!-- Col 1 -->
								<div class="col-lg-6">
									<div class="form-group">
										<label>First Name</label>
										<input type="text" class="form-control" id="first_name" name="first_name"
											value = "<?=$customer['first_name'] ?>"
										/>
									</div>
									<div class="form-group">
										<label>Email</label>
										<input type="text" class="form-control" id="email" name="email"
											value = "<?=$customer['email'] ?>"
										/>
									</div>
									<div class="form-group">
										<label>Major</label>
										<input type="text" class="form-control" id="major" name="major"
											value = "<?=$customer['major'] ?>"
										/>
									</div>
									<div class="form-group">
										<label>Type</label>
										<select name="type" class="form-control" id="type">
											<option val="alumni"
												<?php if ($customer['type'] == 'alumni') echo "selected"; ?>
											>Alumni</option>
											<option val="current"
												<?php if ($customer['type'] == 'current') echo "selected"; ?>
											>Current</option>
										</select>
									</div>
									<div class="form-group">
										<label>Preferred Mail Name</label>
										<input type="text" class="form-control" id="preferred_mail_name" name="preferred_mail_name"
											value = "<?=$customer['preferred_mail_name'] ?>"
										/>
									</div>
									<div class="form-group">
										<label>Home Street 1</label>
										<input type="text" class="form-control" id="home_street_1" name="home_street_1"
											value = "<?=$customer['home_street_1'] ?>"
										/>
									</div>
									<div class="form-group">
										<label>Home Street 2</label>
										<input type="text" class="form-control" id="home_street_2" name="home_street_2"
											value = "<?=$customer['home_street_2'] ?>"
										/>
									</div>
									<div class="form-group">
										<label>State</label>
										<input type="text" class="form-control" id="state" name="state"
											value = "<?=$customer['state'] ?>"
										/>
									</div>
									<div class="form-group">
										<label>Zipcode</label>
										<input type="text" class="form-control" id="zipcode" name="zipcode"
											value = "<?=$customer['zipcode'] ?>"
										/>
									</div>
									
								</div> <!-- col-lg-6 -->
								
								<!-- Col 2 -->
								<div class="col-lg-6">
									<div class="form-group">
										<label>Last Name</label>
										<input type="text" class="form-control" id="last_name" name="last_name"
											value = "<?=$customer['last_name'] ?>"
										/>
									</div>
									<div class="form-group">
										<label>Degree</label>
										<input type="text" class="form-control" id="degree" name="degree"
											value = "<?=$customer['degree'] ?>"
										/>
									</div>
									<div class="form-group">
										<label>School</label>
										<input type="text" class="form-control" id="school" name="school"
											value = "<?=$customer['school'] ?>"
										/>
									</div>
									<div class="form-group">
										<label>Salutation</label>
										<input type="text" class="form-control" id="salutation" name="salutation"
											value = "<?=$customer['salutation'] ?>"
										/>
									</div>
									<div class="form-group">
										<label>Active</label>
										<input type="checkbox" class="form-control" id="active" name="active"
											<?php if ($customer['active']) echo "checked"; ?>
										/>
									</div>
									<div class="form-group">
										<label>Country</label>
										<input type="text" class="form-control" id="country" name="country"
											value = "<?=$customer['country'] ?>"
										/>
									</div>
									<div class="form-group">
										<label>City</label>
										<input type="text" class="form-control" id="city" name="city"
											value = "<?=$customer['city'] ?>"
										/>
									</div>
									<div class="form-group">
										<label>Home Number</label>
										<input type="text" class="form-control" id="home_number" name="home_number"
											value = "<?=$customer['home_number'] ?>"
										/>
									</div>
									<div class="form-group">
										<label>Phone Number</label>
										<input type="text" class="form-control" id="phone_number" name="phone_number"
											value = "<?=$customer['phone_number'] ?>"
										/>
									</div>
									
								</div> <!-- col-lg-6 -->
							</div> <!-- row -->
							
						</fieldset> <!-- base info -->
						
						<fieldset>
							<legend>Work Info</legend>
							
							
						</fieldset>
						
					</form>
					
					<form action="<?=Helper::url('/api/v1/customer/'.$customer['id_customer'])?>/note" method="POST">
						<fieldset>
							<legend>Notes</legend>
						</fieldset>
						
						<div class="form-group">
							<label>New Note</label>
							<textarea class="form-control" rows="5" name="note" placeholder="Add new note..."></textarea>
						</div>
						
						<div class="form-group">
							<input type="hidden" name="user_id" value="1" />
						
							<button type="submit" class="btn btn-primary">Add note</button>
						</div>
						
						<div class="form-group">
							<label>Previous Notes</label>
							<table class="table table-striped" id="data_table">
							  <thead>
								<tr>
									<th>Created at</th>
									<th>Note</th>
								</tr>
							  </thead>
							  <tbody>
								<?php if (isset($notes) && $notes->num_rows > 0): ?>
								<?php while ($note=$notes->fetch_assoc()): ?>
									<tr>
										<td><?=$note['created_at']?></td>
										<td><?=$note['note']?></td>
									</tr>
								<?php endwhile; ?>
								<?php endif; ?>
							  </tbody>
							</table>
						</div>
					</form>
				</div>
			</div>
        
        </div>
      </div>
    </div>
    
  </body>
</html>
