<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>AlumniCRM - Dashboard</title>

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

	<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />

	<link href="https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap.min.css" rel="stylesheet" />
	
	<script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
	
	<script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap.min.js"></script>

    <link href="<?=Helper::url('/media/css/dashboard.css')?>" rel="stylesheet" />

	<script src="<?=Helper::url('/media/js/alumni_single.js')?>"></script>

	<script src="<?=Helper::url('/media/js/global.js')?>"></script>

	<style>
		fieldset {
			margin-bottom: 5%;
		}
	</style>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <!-- Top menu -->
    <?php include "components/top-menu.php"; ?>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
			<!-- LHS Menu -->
			<?php include "components/lhs-menu.php"; ?>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">

			<div class="row" style="margin-bottom:2%;">
				<div class="col-lg-12">
				<?php if ($customer['no_contact']): ?>
					<a class="btn btn-lg btn-success pull-right async_reload" href="<?=Helper::url('/api/v1/customer/'.$customer['id_customer']).'/nocontact/remove'?>"><i class="fa fa-trash"></i> Remove from no contact list</a>
				<?php else:?>
					<a class="btn btn-lg btn-danger pull-right async_reload" href="<?=Helper::url('/api/v1/customer/'.$customer['id_customer']).'/nocontact/add'?>"><i class="fa fa-plus"></i> Add to no contact list</a>
				<?php endif; ?>
				</div>
			</div>
    
			<div class="row">
				<div class="col-lg-12">
					<form action="<?=Helper::url('/api/v1/customer/'.$customer['id_customer'])?>" method="POST">
						<div class="panel panel-default">
							<div class="panel-heading">Base Info</div>
							
							<div class="panel-body">
							
								<div class="row">
									<!-- Col 1 -->
									<div class="col-lg-6">
										<div class="form-group">
											<label>First Name *</label>
											<input type="text" class="form-control" id="first_name" name="first_name"
												value = "<?=$customer_latest['first_name'] ?>"
											/>
										</div>
										<div class="form-group">
											<label>Email *</label>
											<input type="text" class="form-control" id="email" name="email"
												value = "<?=$customer_latest['email'] ?>"
											/>
										</div>
										<div class="form-group">
											<label>Major *</label>
											<input type="text" class="form-control" id="major" name="major"
												value = "<?=$customer_latest['major'] ?>"
											/>
										</div>
										<div class="form-group">
											<label>Gender *</label>
											<select name="gender" class="form-control" id="gender">
												<option value="male"
													<?php if ($customer_latest['gender'] == 'male') echo "selected"; ?>
												>male</option>
												<option value="female"
													<?php if ($customer_latest['gender'] == 'female') echo "selected"; ?>
												>female</option>
											</select>
										</div>
										<div class="form-group">
											<label>Type *</label>
											<select name="type" class="form-control" id="type">
												<option value="alumni"
													<?php if ($customer_latest['type'] == 'alumni') echo "selected"; ?>
												>alumni</option>
												<option value="current"
													<?php if ($customer_latest['type'] == 'current') echo "selected"; ?>
												>current</option>
											</select>
										</div>
										<div class="form-group">
											<label>Preferred Mail Name *</label>
											<input type="text" class="form-control" id="preferred_mail_name" name="preferred_mail_name"
												value = "<?=$customer_latest['preferred_mail_name'] ?>"
											/>
										</div>
										<div class="form-group">
											<label>Home Street 1 *</label>
											<input type="text" class="form-control" id="home_street_1" name="home_street_1"
												value = "<?=$customer_latest['home_street_1'] ?>"
											/>
										</div>
										<div class="form-group">
											<label>Home Street 2</label>
											<input type="text" class="form-control" id="home_street_2" name="home_street_2"
												value = "<?=$customer_latest['home_street_2'] ?>"
											/>
										</div>
										<div class="form-group">
											<label>State *</label>
											<input type="text" class="form-control" id="state" name="state"
												value = "<?=$customer_latest['state'] ?>"
											/>
										</div>
										<div class="form-group">
											<label>Zipcode *</label>
											<input type="text" class="form-control" id="zipcode" name="zipcode"
												value = "<?=$customer_latest['zipcode'] ?>"
											/>
										</div>
										<div class="form-group">
											<label>Major year start *</label>
											<input type="date" class="form-control" id="major_year_start" name="major_year_start"
												value = "<?=$customer_latest['major_year_start'] ?>"
											/>
										</div>
										
										<div class="form-group">
											<button class="btn btn-primary" type="submit">Update</button>
										</div>
										
									</div> <!-- col-lg-6 -->
									
									<!-- Col 2 -->
									<div class="col-lg-6">
										<div class="form-group">
											<label>Last Name *</label>
											<input type="text" class="form-control" id="last_name" name="last_name"
												value = "<?=$customer_latest['last_name'] ?>"
											/>
										</div>
										<div class="form-group">
											<label>Degree *</label>
											<input type="text" class="form-control" id="degree" name="degree"
												value = "<?=$customer_latest['degree'] ?>"
											/>
										</div>
										<div class="form-group">
											<label>School *</label>
											<input type="text" class="form-control" id="school" name="school"
												value = "<?=$customer_latest['school'] ?>"
											/>
										</div>
										<div class="form-group">
											<label>Birthday *</label>
											<input type="date" class="form-control" id="birthday" name="birthday"
												value = "<?=$customer_latest['birthday'] ?>"
											/>
										</div>
										<div class="form-group">
											<label>Salutation *</label>
											<input type="text" class="form-control" id="salutation" name="salutation"
												value = "<?=$customer_latest['salutation'] ?>"
											/>
										</div>
										<div class="form-group">
											<label>Active *</label>
											<input type="checkbox" class="form-control" id="active" name="active"
												<?php if ($customer_latest['active']) echo "checked"; ?>
											/>
										</div>
										<div class="form-group">
											<label>Country *</label>
											<input type="text" class="form-control" id="country" name="country"
												value = "<?=$customer_latest['country'] ?>"
											/>
										</div>
										<div class="form-group">
											<label>City *</label>
											<input type="text" class="form-control" id="city" name="city"
												value = "<?=$customer_latest['city'] ?>"
											/>
										</div>
										<div class="form-group">
											<label>Home Number</label>
											<input type="text" class="form-control" id="home_number" name="home_number"
												value = "<?=$customer_latest['home_number'] ?>"
											/>
										</div>
										<div class="form-group">
											<label>Phone Number *</label>
											<input type="text" class="form-control" id="phone_number" name="phone_number"
												value = "<?=$customer_latest['phone_number'] ?>"
											/>
										</div>
										<div class="form-group">
											<label>Major year end *</label>
											<input type="date" class="form-control" id="major_year_end" name="major_year_end"
												value = "<?=$customer_latest['major_year_end'] ?>"
											/>
										</div>
										
									</div> <!-- col-lg-6 -->
								</div> <!-- row -->
								
								
							</div>
							
						</div> <!-- base info -->
					</form>
					
					<form action="<?=Helper::url('/api/v1/customer/'.$customer['id_customer']).'/work' ?>" method="POST">
						<div class="panel panel-default">
							<div class="panel-heading">Work Info</div>
							
							<div class="panel-body">
							
								<div class="row">

									<?php if ($works->num_rows > 0): ?>
									<div class="col-lg-12">
										<div class="form-group">
											<h4>Work positions</h4>
										</div>
										
										<ul class="list-group">
											
											<?php while($work = $works->fetch_assoc()): ?>
												<li class="list-group-item">
													 <h4 class="list-group-item-heading"><?=$work['title']?></h4>
													 <p class="list-group-item-text"><?=$work['date_end']?> - <?=$work['date_start']?></p>
												</li>
											<?php endwhile; ?>	
											
										</ul>
									</div>
									<?php endif; ?>

									<div class="col-lg-12">
										<div class="form-group">
											<h4>Add new work position</h4>
										</div>
									
										<div class="form-group col-lg-6">
											<label>Title *</label>
											<input type="text" class="form-control" id="work_title" name="title"
												
											/>
										</div>
										<div class="form-group col-lg-6">
											<label>Address Line 1 *</label>
											<input type="text" class="form-control" id="work_address_line1" name="address_line1"
												
											/>
										</div>
										<div class="form-group col-lg-6">
											<label>Address Line 2 *</label>
											<input type="text" class="form-control" id="work_address_line2" name="address_line2"
												
											/>
										</div>
										<div class="form-group col-lg-6">
											<label>City *</label>
											<input type="text" class="form-control" id="work_city" name="city"
												
											/>
										</div>
										<div class="form-group col-lg-6">
											<label>State *</label>
											<input type="text" class="form-control" id="work_state" name="state"
												
											/>
										</div>
										<div class="form-group col-lg-6">
											<label>Country *</label>
											<input type="text" class="form-control" id="work_country" name="country"
												
											/>
										</div>
										<div class="form-group col-lg-6">
											<label>Zipcode *</label>
											<input type="text" class="form-control" id="work_zipcode" name="zipcode"
												
											/>
										</div>
										<div class="form-group col-lg-6">
											<label>Field *</label>
											<input type="text" class="form-control" id="work_field" name="field"
												
											/>
										</div>
										<div class="form-group col-lg-6">
											<label>Date Start *</label>
											<input type="date" class="form-control" id="work_date_start" name="date_start"
												
											/>
										</div>
										<div class="form-group col-lg-6">
											<label>Date End *</label>
											<input type="date" class="form-control" id="work_date_end" name="date_end"
												
											/>
										</div>
										<div class="form-group col-lg-6">
											<button type="submit" class="btn btn-primary">Add position</button>
										</div>
									</div>
									
								</div>
							</div>
								
						</div>
					</form>

					
					<form action="<?=Helper::url('/api/v1/customer/'.$customer['id_customer'])?>/note" method="POST">
						<div class="panel panel-default">
							<div class="panel-heading">Notes</div>
							
							<div class="panel-body">

								<div class="row">
									<div class="col-lg-6">
										<div class="form-group">
											<label>New Note *</label>
											<textarea class="form-control" rows="5" name="note" placeholder="Add new note..."></textarea>
										</div>
										
										<div class="form-group">
											<input type="hidden" name="user_id" value="<?=$admin_user_id?>" />
										
											<button type="submit" class="btn btn-primary">Add note</button>
										</div>
									</div>
									
									<div class="col-lg-6">
										<div class="form-group">
											<label>Previous Notes</label>
											<table class="table table-striped" id="data_table">
											  <thead>
												<tr>
													<th>Created at</th>
													<th>Note</th>
													<th>Created By</th>
													<th>Actions</th>
												</tr>
											  </thead>
											  <tbody>
												<?php if (isset($notes) && $notes->num_rows > 0): ?>
												<?php while ($note=$notes->fetch_assoc()): ?>
													<tr>
														<td><?=$note['created_at']?></td>
														<td><?=$note['note']?></td>
														<td><?=$note['admin_name']?></td>
														<td><a href="<?=Helper::url('/api/v1/customer/'.$customer['id_customer']."/note/".$note['id_note'])."/delete"?>" class="btn btn-danger async_reload"><i class="fa fa-trash"></i></a>
														<a href="#" class="btn btn-primary async_reload"><i class="fa fa-edit"></i></a></td>
													</tr>
												<?php endwhile; ?>
												<?php endif; ?>
											  </tbody>
											</table>
										</div>
									</div> <!-- col -->
								</div> <!-- row -->
							</div>
								
						</div>
					</form>
				</div>
			</div>
        
			<div class="row">
				<div class="col-lg-12">
					<div class="panel panel-default">
						<div class="panel-heading">User access token</div>
						
						<div class="panel-body">
							<form action="<?=Helper::url('/api/v1/customer/'.$customer['id_customer'])?>/token" method="POST">
								<div class="form-group">
									<input class="form-control" type="text" name="token" value="<?=$customer['token']?>" readonly />
								</div>
								<div class="form-group">
									<button class="btn btn-primary" type="submit">Generate new token</button>
								</div>
								<div class="form-group">
									<a class="btn btn-default" href="#"><i class="fa fa-envelope"></i> Send user update email</a>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
        
        </div>
      </div>
    </div>
    
	<div class="modal fade" tabindex="-1" role="dialog" id="error_modal">
	  <div class="modal-dialog" role="document">
		<div class="modal-content">
		  <div class="modal-header">
		    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		    <h4 class="modal-title">Error</h4>
		  </div>
		  <div class="modal-body">
		    <div class="row">
				<div class="col-lg-12">
					<ul id="errors_list" style="color:red;">
					</ul>
				</div>
			</div>
		  </div>
		  <div class="modal-footer">
		    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
		  </div>
		</div><!-- /.modal-content -->
	  </div><!-- /.modal-dialog -->
	</div><!-- /.modal -->

  </body>
</html>
